
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Nov 28 07:01:40 CST 2012
//----------------------------------------------------

package scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFTBRACKET = 29;
  public static final int INCREMENT = 10;
  public static final int EQUALS = 12;
  public static final int ENTERO = 33;
  public static final int RIGHTBRACKET = 30;
  public static final int NOTEQUAL = 17;
  public static final int GREATER = 14;
  public static final int INT = 2;
  public static final int LESS = 16;
  public static final int DECREMENT = 11;
  public static final int WRITE = 9;
  public static final int NOT = 20;
  public static final int SEMICOLON = 31;
  public static final int AND = 19;
  public static final int LESSEQUAL = 15;
  public static final int OR = 18;
  public static final int COMMA = 32;
  public static final int LISTSTRING = 36;
  public static final int ASSIGN = 21;
  public static final int SUBTRACTION = 23;
  public static final int IF = 4;
  public static final int ID = 35;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int TRUE = 37;
  public static final int error = 1;
  public static final int MODULO = 26;
  public static final int VOID = 3;
  public static final int GREATEREQUAL = 13;
  public static final int RIGHTPAR = 28;
  public static final int ELSE = 5;
  public static final int READ = 8;
  public static final int WHILE = 6;
  public static final int ADDITION = 22;
  public static final int LEFTPAR = 27;
  public static final int FALSE = 38;
  public static final int DIVISION = 25;
  public static final int MULTIPLICATION = 24;
  public static final int FLOTANTE = 34;
}

